#!/bin/bash -e

# Copyright The IETF Trust 2019, All Rights Reserved
# Copyright (c) 2018 Cisco and/or its affiliates.
# This software is licensed to you under the terms of the Apache License, Version 2.0 (the "License").
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# The code, technical concepts, and all information contained herein, are the property of Cisco Technology, Inc.
# and/or its affiliated entities, under various laws including copyright, international treaties, patent,
# and/or contract. Any use of the material herein must be in accordance with the terms of the License.
# All rights not expressly granted by the License are reserved.
# Unless required by applicable law or agreed to separately in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.
#
START=$(date "+%s")
python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "" --status "In Progress" --filename "cronjob-daily"
#source activate
source "$CONF"/configure.sh
date +"%c: Downloading from GitHub YangModels"
{
  DOWNLOAD_GITHUB_STATUS=$(./run_download_github.sh)
} || {
  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "GitHub download failed" --filename "cronjob-daily" && exit 1
}
date +"%c: Starting run_ietf_module_extraction.sh"
{
  IETF_MODULES_EXTRACTION_MESSAGE=$("$VIRTUAL_ENV"/ietf_modules_extraction/run_ietf_module_extraction.sh)
} || {
  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "IETF modules extraction failed, check the logs for more details: $LOGS/extract_ietf_modules.log" --filename "cronjob-daily" && exit 1
}
date +"%c: Starting run_module_compilation.sh"
{
  MODULES_COMPILATION_MESSAGE=$("$VIRTUAL_ENV"/modules_compilation/run_module_compilation.sh)
} || {
  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "Modules compilation failed, check the logs for more details: $LOGS/compile_modules.log" --filename "cronjob-daily" && exit 1
}
date +"%c: Starting rename_file_backup.py"
mkdir -p "$BACKUPDIR"
python "$VIRTUAL_ENV"/rename_file_backup.py
date +"%c: Starting run_generate_main_page.sh"
{
  MAIN_PAGE_GENERATION_MESSAGE=$("$VIRTUAL_ENV"/main_page_generation/run_generate_main_page.sh)
} || {
  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "Main page generation failed" --filename "cronjob-daily" && exit 1
}
date +"%c: Starting run_generate_figures_and_stats.sh"
{
  FIGURES_AND_STATS_GENERATION_MESSAGE=$("$VIRTUAL_ENV"/figures_and_stats/run_generate_figures_and_stats.sh)
} || {
  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "Figures and stats generation failed, check the logs for more details: $LOGS/generate_figures_and_stats.log" --filename "cronjob-daily" && exit 1
}

# This are simple files for other Yang Catalog to know which files have been created
cd "$WEB_PRIVATE"
ls *.json > json_links
END=$(date "+%s")
python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$END" --status "Success" --filename "cronjob-daily" --load-messages-json --messages '{"label":"run_download_github.sh","message":"'"$DOWNLOAD_GITHUB_STATUS"'"}' '{"label":"run_ietf_module_extraction.sh","message":"'"$IETF_MODULES_EXTRACTION_MESSAGE"'"}' '{"label":"run_module_compilation.sh","message":"'"$MODULES_COMPILATION_MESSAGE"'"}' '{"label":"run_generate_main_page.sh","message":"'"$MAIN_PAGE_GENERATION_MESSAGE"'"}' '{"label":"run_generate_figures_and_stats.sh","message":"'"$FIGURES_AND_STATS_GENERATION_MESSAGE"'"}'
date +"%c: End of $0"
