#!/bin/bash -e

# Copyright The IETF Trust 2019, All Rights Reserved
# Copyright (c) 2018 Cisco and/or its affiliates.
# This software is licensed to you under the terms of the Apache License, Version 2.0 (the "License").
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
# The code, technical concepts, and all information contained herein, are the property of Cisco Technology, Inc.
# and/or its affiliated entities, under various laws including copyright, international treaties, patent,
# and/or contract. Any use of the material herein must be in accordance with the terms of the License.
# All rights not expressly granted by the License are reserved.
# Unless required by applicable law or agreed to separately in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied.
#
START=$(date "+%s")
#source activate
source "$CONF"/configure.sh
date +"%c: Downloading from GitHub YangModels"
./run_download_github.sh
date +"%c: Starting run_ietf_module_extraction.sh"
"$VIRTUAL_ENV"/ietf_modules_extraction/run_ietf_module_extraction.sh
date +"%c: Starting run_module_compilation.sh"
"$VIRTUAL_ENV"/modules_compilation/run_module_compilation.sh
date +"%c: Starting rename_file_backup.py"
mkdir -p "$BACKUPDIR"
python "$VIRTUAL_ENV"/rename_file_backup.py
date +"%c: Starting run_generate_main_page.sh"
"$VIRTUAL_ENV"/main_page_generation/run_generate_main_page.sh
date +"%c: Starting run_generate_figures_and_stats.sh"
"$VIRTUAL_ENV"/figures_and_stats/run_generate_figures_and_stats.sh

# This simple files for other Yang Catalog to know which files have been created
cd "$WEB_PRIVATE"
ls *.json > json_links
END=$(date "+%s")
# shellcheck disable=SC2086
python "$VIRTUAL_ENV"/job_log.py --start "$START" --end $END --status "Success" --filename "cronjob-daily"
date +"%c: End of $0"
